import type { DashboardData } from "@/types";

export const mockDashboard: DashboardData = {
  user: { name: "Alexander S.", tarif: "ActiveMed-U", kasse: "AXA" },
  currentYear: new Date().getFullYear(),
  vorgangCount: 7,
  einsparpotenzialCount: 3,
  monthsWithData: 4,
  jahresausgaben: 1847,
  eigenanteil: 312,
  eigenanteilBreakdown: {
    abgelehnt: 87,
    stilleKuerzungen: 127,
    selbstbehalt: 150,
    offeneRechnungen: 0,
  },
  // Erstattungsquote = erstattet / (eingereicht - selbstbehalt) = 620/(820-150) ≈ 93%
  erstattungsquote: 93,
  einsparpotenzial: 63,              // GOÄ §12 Ärzte (rein GOÄ-basiert)
  widerspruchPotenzialKasse: 74,     // Positionen aktionstyp=widerspruch_kasse (Labor-Ablehnung)
  korrekturArztPotenzial: 63,
  widerspruchVerfahren: [],
  // Prognose: data through month 4 (April) → × 12/4
  prognose: Math.round(1847 / 4 * 12),
  vorgaenge: [
    {
      id: "1",
      datum: "14.03.2025",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 218.47,
      einsparpotenzial: 63.80,
      status: "pruefen",
      goaZiffern: ["GOÄ 3", "GOÄ 5", "GOÄ 6"],
      faktor: 3.5,
      flagged: true,
      flagReason: "Faktor 3,5× ohne §12-Begründung",
    },
    {
      id: "2",
      datum: "02.03.2025",
      arzt: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      betrag: 147.20,
      einsparpotenzial: 74.00,
      status: "abgelehnt",
      goaZiffern: ["GOÄ 3550", "GOÄ A3695a"],
      flagged: true,
      flagReason: "Analogziffer AXA-Ablehnung",
    },
    {
      id: "3",
      datum: "18.02.2025",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 214.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 750", "GOÄ 760"],
      faktor: 2.1,
    },
    {
      id: "4",
      datum: "05.01.2025",
      arzt: "Praxis Zentrum Sehen",
      fachrichtung: "Augenheilkunde",
      betrag: 152.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 1200", "GOÄ 1240"],
      faktor: 1.8,
    },
    {
      id: "5",
      datum: "12.06.2024",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 186.40,
      status: "erstattet",
      faktor: 3.0,
      flagged: true,
      flagReason: "Faktor 3,0× ohne §12-Begründung",
    },
    {
      id: "6",
      datum: "08.02.2024",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 98.50,
      status: "erstattet",
      faktor: 2.3,
    },
  ],
  aerzte: [
    {
      id: "hartmann",
      name: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      ort: "München",
      besuche: 4,
      gesamtBetrag: 687,
      avgFaktor: 2.9,
      flagged: true,
      erstattetVonKasse: 412,
      abgelehntVonKasse: 63,
      eingereichtBeiKasse: 475,
      faktorVerlauf: [
        { datum: "Mär '23", faktor: 1.8 },
        { datum: "Nov '23", faktor: 2.3 },
        { datum: "Jun '24", faktor: 3.0 },
        { datum: "Mär '25", faktor: 3.5 },
      ],
      alerts: [
        "Faktor stieg von 1,8× auf 3,5× — ohne §12-Begründung",
        "GOÄ Nr. 3 + Nr. 6 gleichzeitig abgerechnet (unplausible Kumulation, <3% der Internisten)",
      ],
    },
    {
      id: "schulz",
      name: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      ort: "München",
      besuche: 2,
      gesamtBetrag: 214,
      avgFaktor: 2.2,
      flagged: false,
      erstattetVonKasse: 198,
      abgelehntVonKasse: 0,
      eingereichtBeiKasse: 198,
      faktorVerlauf: [
        { datum: "Feb '24", faktor: 2.3 },
        { datum: "Feb '25", faktor: 2.1 },
      ],
      alerts: [],
    },
    {
      id: "labor",
      name: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      ort: "München",
      besuche: 3,
      gesamtBetrag: 312,
      avgFaktor: 1.0,
      flagged: true,
      erstattetVonKasse: 73,
      abgelehntVonKasse: 74,
      eingereichtBeiKasse: 147,
      faktorVerlauf: [],
      alerts: ["38% Ablehnungsrate bei AXA für Analogziffer A3695a"],
    },
  ],
  kasse: {
    kasseName: "AXA",
    erstattungsquote: 93,
    erstattungsquoteAvg: 89,
    ablehnungsrate: [0, 18],  // 2 points: start-of-year baseline vs current month
    ablehnungsrateReal: 18,
    stilleKuerzungTotal: 127,
    stilleKuerzungCount: 5,
    stilleKuerzungen: [
      { kategorie: "Laborpositionen", betrag: 74, vorgaenge: 3 },
      { kategorie: "Internist Faktoren", betrag: 38, vorgaenge: 2 },
      { kategorie: "Sonstige", betrag: 15, vorgaenge: 2 },
    ],
    totalAbgelehnt: 147,
    totalSelbstbehalt: 150,
    widerspruchPotenzial: 147,
    fachgruppenStats: [
      { fach: "Innere Medizin", vorgaenge: 3, eingereicht: 687, abgelehnt: 127, ablehnungsquote: 18 },
      { fach: "Labor",          vorgaenge: 4, eingereicht: 312, abgelehnt: 74,  ablehnungsquote: 24 },
      { fach: "Dermatologie",   vorgaenge: 2, eingereicht: 214, abgelehnt: 0,   ablehnungsquote: 0  },
    ],
  },
  ausgabenNachFach: [
    { fach: "Innere Medizin", betrag: 687, icon: "❤️", farbe: "#fca5a5" },
    { fach: "Labor", betrag: 312, icon: "🔬", farbe: "#c4b5fd" },
    { fach: "Dermatologie", betrag: 214, icon: "🧬", farbe: "#93c5fd" },
    { fach: "Augenheilkunde", betrag: 152, icon: "👁️", farbe: "#6ee7b7" },
    { fach: "Weitere", betrag: 482, icon: "💊", farbe: "#e2e8f0" },
  ],
  vorsorgeLeistungen: [
    {
      id: "v1",
      name: "Internist Jahres-Check",
      icon: "❤️",
      fachgebiet: "Innere Medizin",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-14",
      naechstesDatum: "2026-03-14",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v2",
      name: "Labor-Basisprofil",
      icon: "🔬",
      fachgebiet: "Labordiagnostik",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-02",
      naechstesDatum: "2026-03-02",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v3",
      name: "Augenarzt Sehtest",
      icon: "👁️",
      fachgebiet: "Augenheilkunde",
      empfIntervallMonate: 24,
      letzteDatum: "2025-01-05",
      naechstesDatum: "2027-01-05",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v4",
      name: "Dermatologie Hautscreening",
      icon: "🧬",
      fachgebiet: "Dermatologie",
      empfIntervallMonate: 24,
      letzteDatum: "2025-02-18",
      naechstesDatum: "2027-02-18",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v5",
      name: "Zahnarzt Prophylaxe",
      icon: "🦷",
      fachgebiet: "Zahnarzt",
      empfIntervallMonate: 6,
      letzteDatum: null,
      naechstesDatum: null,
      status: "faellig",
      axaLeistung: true,
    },
  ],
};
