import type { DashboardData } from "@/types";
import type { KasseBescheid } from "@/app/kassenabrechnung/page";
import type { WiderspruchFall } from "@/app/widersprueche/page";
import type { ArztAkteData } from "@/app/aerzte/AerzteClient";

export const mockDashboard: DashboardData = {
  user: { name: "Alexander S.", tarif: "ActiveMed-U", kasse: "AXA" },
  currentYear: new Date().getFullYear(),
  vorgangCount: 7,
  einsparpotenzialCount: 3,
  monthsWithData: 4,
  jahresausgaben: 1847,
  eigenanteil: 312,
  eigenanteilBreakdown: {
    abgelehnt: 87,
    stilleKuerzungen: 127,
    selbstbehalt: 150,
    offeneRechnungen: 0,
  },
  // Erstattungsquote = erstattet / (eingereicht - selbstbehalt) = 620/(820-150) ≈ 93%
  erstattungsquote: 93,
  einsparpotenzial: 63,              // GOÄ §12 Ärzte (rein GOÄ-basiert)
  widerspruchPotenzialKasse: 74,     // Positionen aktionstyp=widerspruch_kasse (Labor-Ablehnung)
  korrekturArztPotenzial: 63,
  widerspruchVerfahren: [],
  // Prognose: data through month 4 (April) → × 12/4
  prognose: Math.round(1847 / 4 * 12),
  vorgaenge: [
    {
      id: "1",
      datum: "14.03.2025",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 218.47,
      einsparpotenzial: 63.80,
      status: "pruefen",
      goaZiffern: ["GOÄ 3", "GOÄ 5", "GOÄ 6"],
      faktor: 3.5,
      flagged: true,
      flagReason: "Faktor 3,5× ohne §12-Begründung",
    },
    {
      id: "2",
      datum: "02.03.2025",
      arzt: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      betrag: 147.20,
      einsparpotenzial: 74.00,
      status: "abgelehnt",
      goaZiffern: ["GOÄ 3550", "GOÄ A3695a"],
      flagged: true,
      flagReason: "Analogziffer AXA-Ablehnung",
    },
    {
      id: "3",
      datum: "18.02.2025",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 214.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 750", "GOÄ 760"],
      faktor: 2.1,
    },
    {
      id: "4",
      datum: "05.01.2025",
      arzt: "Praxis Zentrum Sehen",
      fachrichtung: "Augenheilkunde",
      betrag: 152.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 1200", "GOÄ 1240"],
      faktor: 1.8,
    },
    {
      id: "5",
      datum: "12.06.2024",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 186.40,
      status: "erstattet",
      faktor: 3.0,
      flagged: true,
      flagReason: "Faktor 3,0× ohne §12-Begründung",
    },
    {
      id: "6",
      datum: "08.02.2024",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 98.50,
      status: "erstattet",
      faktor: 2.3,
    },
  ],
  aerzte: [
    {
      id: "hartmann",
      name: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      ort: "München",
      besuche: 4,
      gesamtBetrag: 687,
      avgFaktor: 2.9,
      flagged: true,
      erstattetVonKasse: 412,
      abgelehntVonKasse: 63,
      eingereichtBeiKasse: 475,
      faktorVerlauf: [
        { datum: "Mär '23", faktor: 1.8 },
        { datum: "Nov '23", faktor: 2.3 },
        { datum: "Jun '24", faktor: 3.0 },
        { datum: "Mär '25", faktor: 3.5 },
      ],
      alerts: [
        "Faktor stieg von 1,8× auf 3,5× — ohne §12-Begründung",
        "GOÄ Nr. 3 + Nr. 6 gleichzeitig abgerechnet (unplausible Kumulation, <3% der Internisten)",
      ],
    },
    {
      id: "schulz",
      name: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      ort: "München",
      besuche: 2,
      gesamtBetrag: 214,
      avgFaktor: 2.2,
      flagged: false,
      erstattetVonKasse: 198,
      abgelehntVonKasse: 0,
      eingereichtBeiKasse: 198,
      faktorVerlauf: [
        { datum: "Feb '24", faktor: 2.3 },
        { datum: "Feb '25", faktor: 2.1 },
      ],
      alerts: [],
    },
    {
      id: "labor",
      name: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      ort: "München",
      besuche: 3,
      gesamtBetrag: 312,
      avgFaktor: 1.0,
      flagged: true,
      erstattetVonKasse: 73,
      abgelehntVonKasse: 74,
      eingereichtBeiKasse: 147,
      faktorVerlauf: [],
      alerts: ["38% Ablehnungsrate bei AXA für Analogziffer A3695a"],
    },
  ],
  kasse: {
    kasseName: "AXA",
    erstattungsquote: 93,
    erstattungsquoteAvg: 89,
    ablehnungsrate: [0, 18],  // 2 points: start-of-year baseline vs current month
    ablehnungsrateReal: 18,
    stilleKuerzungTotal: 127,
    stilleKuerzungCount: 5,
    stilleKuerzungen: [
      { kategorie: "Laborpositionen", betrag: 74, vorgaenge: 3 },
      { kategorie: "Internist Faktoren", betrag: 38, vorgaenge: 2 },
      { kategorie: "Sonstige", betrag: 15, vorgaenge: 2 },
    ],
    totalAbgelehnt: 147,
    totalSelbstbehalt: 150,
    widerspruchPotenzial: 147,
    fachgruppenStats: [
      { fach: "Innere Medizin", vorgaenge: 3, eingereicht: 687, abgelehnt: 127, ablehnungsquote: 18 },
      { fach: "Labor",          vorgaenge: 4, eingereicht: 312, abgelehnt: 74,  ablehnungsquote: 24 },
      { fach: "Dermatologie",   vorgaenge: 2, eingereicht: 214, abgelehnt: 0,   ablehnungsquote: 0  },
    ],
  },
  ausgabenNachFach: [
    { fach: "Innere Medizin", betrag: 687, icon: "❤️", farbe: "#fca5a5" },
    { fach: "Labor", betrag: 312, icon: "🔬", farbe: "#c4b5fd" },
    { fach: "Dermatologie", betrag: 214, icon: "🧬", farbe: "#93c5fd" },
    { fach: "Augenheilkunde", betrag: 152, icon: "👁️", farbe: "#6ee7b7" },
    { fach: "Weitere", betrag: 482, icon: "💊", farbe: "#e2e8f0" },
  ],
  vorsorgeLeistungen: [
    {
      id: "v1",
      name: "Internist Jahres-Check",
      icon: "❤️",
      fachgebiet: "Innere Medizin",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-14",
      naechstesDatum: "2026-03-14",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v2",
      name: "Labor-Basisprofil",
      icon: "🔬",
      fachgebiet: "Labordiagnostik",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-02",
      naechstesDatum: "2026-03-02",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v3",
      name: "Augenarzt Sehtest",
      icon: "👁️",
      fachgebiet: "Augenheilkunde",
      empfIntervallMonate: 24,
      letzteDatum: "2025-01-05",
      naechstesDatum: "2027-01-05",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v4",
      name: "Dermatologie Hautscreening",
      icon: "🧬",
      fachgebiet: "Dermatologie",
      empfIntervallMonate: 24,
      letzteDatum: "2025-02-18",
      naechstesDatum: "2027-02-18",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v5",
      name: "Zahnarzt Prophylaxe",
      icon: "🦷",
      fachgebiet: "Zahnarzt",
      empfIntervallMonate: 6,
      letzteDatum: null,
      naechstesDatum: null,
      status: "faellig",
      axaLeistung: true,
    },
  ],
};

// ── Mock Rechnungen (VorgangRow shape for RechnungenClient) ──────────────────
export const mockRechnungen = [
  {
    id: "demo-1",
    datum: "14.03.2025",
    arzt: "Dr. med. Klaus Hartmann",
    fachrichtung: "Innere Medizin",
    betrag: 218.47,
    betragErstattet: undefined,
    einsparpotenzial: 63.80,
    status: "pruefen",
    flagged: true,
    flagReason: "Faktor 3,5× ohne §12-Begründung · GOÄ 3+6 Kumulationsrisiko",
    faktor: 3.5,
    goaZiffern: ["GOÄ 3", "GOÄ 5", "GOÄ 6"],
    hasPdf: false,
    hasKassePdf: false,
    claudeAnalyse: {
      arztName: "Dr. med. Klaus Hartmann",
      arztFachgebiet: "Innere Medizin",
      rechnungsdatum: "2025-03-14",
      betragGesamt: 218.47,
      maxFaktor: 3.5,
      flagFaktorUeberSchwellenwert: true,
      flagFehlendeBegrundung: true,
      einsparpotenzial: 63.80,
      zusammenfassung: "Drei GOÄ-Auffälligkeiten erkannt: Faktor 3,5× auf GOÄ Nr. 3 und Nr. 6 übersteigt den Schwellenwert (§12 GOÄ verlangt schriftliche Begründung ab 2,3×). Zusätzlich werden GOÄ 3 und GOÄ 6 gleichzeitig abgerechnet — diese Kombination ist bei weniger als 3% aller Internisten üblich und gilt als unplausible Kumulation. Einsparpotenzial durch Beanstandung beim Arzt: 63,80 €.",
      fehlendePflichtangaben: [],
      flagRechnungUnvollstaendig: false,
      goaePositionen: [
        {
          ziffer: "3",
          bezeichnung: "Eingehende, das gewöhnliche Maß übersteigende Beratung (mind. 10 Min.)",
          faktor: 3.5,
          betrag: 28.68,
          flag: "hoch",
          kumulationsrisiko: true,
          kumulationskonflikt: "GOÄ 3 + GOÄ 6 gleichzeitig — unplausible Kumulation (<3% der Internisten)",
          begruendungsqualitaet: "fehlend",
          axaRisiko: "hoch",
          risikohinweis: "AXA lehnt Faktor >2,3× ohne §12-Begründung regelmäßig ab",
        },
        {
          ziffer: "5",
          bezeichnung: "Symptombezogene Untersuchung",
          faktor: 3.5,
          betrag: 19.24,
          flag: "hoch",
          kumulationsrisiko: false,
          begruendungsqualitaet: "fehlend",
          axaRisiko: "mittel",
          risikohinweis: "Faktor 3,5× ohne Begründung — bitte Arzt um Ergänzung bitten",
        },
        {
          ziffer: "6",
          bezeichnung: "Vollständige körperliche Untersuchung mindestens eines Organsystems",
          faktor: 3.5,
          betrag: 16.88,
          flag: "hoch",
          kumulationsrisiko: true,
          kumulationskonflikt: "GOÄ 6 + GOÄ 3 gleichzeitig — bei gleichem Termin nicht kombinierbar",
          begruendungsqualitaet: "fehlend",
          axaRisiko: "hoch",
          risikohinweis: "Häufigster Ablehnungsgrund bei AXA Innere Medizin",
        },
        {
          ziffer: "75",
          bezeichnung: "Schutzimpfung (subkutan, intramuskulär oder intrakutan)",
          faktor: 2.3,
          betrag: 6.72,
          flag: "ok",
          axaRisiko: null,
        },
        {
          ziffer: "250",
          bezeichnung: "Blutentnahme durch Venenpunktion",
          faktor: 1.0,
          betrag: 4.43,
          flag: "ok",
          axaRisiko: null,
        },
      ],
    },
    kasseAnalyse: null,
    kassenbescheid: null,
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-2",
    datum: "02.03.2025",
    arzt: "Labor Müller GmbH",
    fachrichtung: "Labordiagnostik",
    betrag: 147.20,
    betragErstattet: 73.20,
    einsparpotenzial: 74.00,
    status: "abgelehnt",
    flagged: true,
    flagReason: "GOÄ A3695a von AXA abgelehnt — Widerspruch empfohlen (72% Erfolg)",
    faktor: undefined,
    goaZiffern: ["GOÄ 3550", "GOÄ A3695a"],
    hasPdf: false,
    hasKassePdf: true,
    claudeAnalyse: {
      arztName: "Labor Müller GmbH",
      arztFachgebiet: "Labordiagnostik",
      rechnungsdatum: "2025-03-02",
      betragGesamt: 147.20,
      maxFaktor: 1.0,
      flagFaktorUeberSchwellenwert: false,
      flagFehlendeBegrundung: false,
      einsparpotenzial: 0,
      zusammenfassung: "Die Laborrechnung enthält eine Analogziffer (GOÄ A3695a) für ein erweitertes Schilddrüsen-/Hormonpanel. Die Leistung ist medizinisch korrekt kodiert. AXA lehnt Analogziffern im Laborbereich häufig pauschal ab — das ist rechtlich angreifbar.",
      flagRechnungUnvollstaendig: false,
      fehlendePflichtangaben: [],
      goaePositionen: [
        {
          ziffer: "3550",
          bezeichnung: "Hormonstatus: TSH, fT3, fT4 — quantitative Bestimmung",
          faktor: 1.0,
          betrag: 73.20,
          flag: "ok",
          axaRisiko: null,
        },
        {
          ziffer: "A3695a",
          bezeichnung: "Erweitertes Hormonpanel (Analogziffer nach §6 Abs. 2) — Anti-TPO, Anti-Thyreoglobulin",
          faktor: 1.0,
          betrag: 74.00,
          flag: "pruefe",
          analog: true,
          axaRisiko: "hoch",
          risikohinweis: "AXA lehnt diese Analogziffer in 38% der Fälle ab — Widerspruch hat aber 72% Erfolgsquote",
        },
      ],
    },
    kasseAnalyse: null,
    kassenbescheid: {
      id: "demo-kasse-1",
      bescheiddatum: "2025-03-20",
      referenznummer: "AXA-2025-001234",
      betragErstattet: 73.20,
      betragAbgelehnt: 74.00,
      widerspruchEmpfohlen: true,
      widerspruchStatus: "erstellt",
      widerspruchErfolgswahrscheinlichkeit: 72,
    },
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-3",
    datum: "18.02.2025",
    arzt: "Dr. med. Julia Schulz",
    fachrichtung: "Dermatologie",
    betrag: 214.00,
    betragErstattet: 214.00,
    einsparpotenzial: undefined,
    status: "erstattet",
    flagged: false,
    flagReason: undefined,
    faktor: 2.1,
    goaZiffern: ["GOÄ 750", "GOÄ 760"],
    hasPdf: false,
    hasKassePdf: true,
    claudeAnalyse: {
      arztName: "Dr. med. Julia Schulz",
      arztFachgebiet: "Dermatologie",
      rechnungsdatum: "2025-02-18",
      betragGesamt: 214.00,
      maxFaktor: 2.1,
      flagFaktorUeberSchwellenwert: false,
      flagFehlendeBegrundung: false,
      einsparpotenzial: 0,
      zusammenfassung: "Unauffällige Rechnung. Faktor 2,1× liegt im üblichen Rahmen für dermatologische Behandlungen. Alle Positionen sind plausibel kombinierbar.",
      flagRechnungUnvollstaendig: false,
      fehlendePflichtangaben: [],
      goaePositionen: [
        {
          ziffer: "750",
          bezeichnung: "Behandlung einer Hauterkrankung, je Sitzung",
          faktor: 2.1,
          betrag: 83.47,
          flag: "ok",
          axaRisiko: null,
        },
        {
          ziffer: "760",
          bezeichnung: "Dermatologische Phototherapie (UVA/UVB), je Sitzung",
          faktor: 2.1,
          betrag: 130.53,
          flag: "ok",
          axaRisiko: null,
        },
      ],
    },
    kasseAnalyse: null,
    kassenbescheid: {
      id: "demo-kasse-2",
      bescheiddatum: "2025-03-05",
      referenznummer: "AXA-2025-000987",
      betragErstattet: 214.00,
      betragAbgelehnt: 0,
      widerspruchEmpfohlen: false,
      widerspruchStatus: "keiner",
      widerspruchErfolgswahrscheinlichkeit: null,
    },
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-4",
    datum: "05.01.2025",
    arzt: "Praxis Zentrum Sehen",
    fachrichtung: "Augenheilkunde",
    betrag: 152.00,
    betragErstattet: 152.00,
    einsparpotenzial: undefined,
    status: "erstattet",
    flagged: false,
    flagReason: undefined,
    faktor: 1.8,
    goaZiffern: ["GOÄ 1200", "GOÄ 1240"],
    hasPdf: false,
    hasKassePdf: false,
    claudeAnalyse: {
      arztName: "Praxis Zentrum Sehen",
      arztFachgebiet: "Augenheilkunde",
      rechnungsdatum: "2025-01-05",
      betragGesamt: 152.00,
      maxFaktor: 1.8,
      flagFaktorUeberSchwellenwert: false,
      flagFehlendeBegrundung: false,
      einsparpotenzial: 0,
      zusammenfassung: "Unauffällige Rechnung. Faktor 1,8× liegt deutlich unter dem Schwellenwert. Alle GOÄ-Positionen sind korrekt und vollständig dokumentiert.",
      flagRechnungUnvollstaendig: false,
      fehlendePflichtangaben: [],
      goaePositionen: [
        {
          ziffer: "1200",
          bezeichnung: "Untersuchung des Augenhintergrundes (Ophthalmoskopie)",
          faktor: 1.8,
          betrag: 61.20,
          flag: "ok",
          axaRisiko: null,
        },
        {
          ziffer: "1240",
          bezeichnung: "Messung des Augeninnendrucks (Tonometrie)",
          faktor: 1.8,
          betrag: 90.80,
          flag: "ok",
          axaRisiko: null,
        },
      ],
    },
    kasseAnalyse: null,
    kassenbescheid: null,
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
] as const;

// ── Mock Kassenabrechnungen ───────────────────────────────────────────────────
export const mockKasseBescheide: KasseBescheid[] = [
  {
    id: "demo-kasse-1",
    bescheiddatum: "2025-03-20",
    referenznummer: "AXA-2025-001234",
    betrag_eingereicht: 365.67,
    betrag_erstattet: 218.47,
    betrag_abgelehnt: 147.20,
    widerspruch_empfohlen: true,
    widerspruch_status: "erstellt",
    arzt_reklamation_status: "erstellt",
    selbstbehalt_abgezogen: null,
    selbstbehalt_verbleibend: null,
    selbstbehalt_jahresgrenze: null,
    pdf_storage_path: null,
    kasse_analyse: {
      referenznummer: "AXA-2025-001234",
      bescheiddatum: "2025-03-20",
      betragEingereicht: 365.67,
      betragErstattet: 218.47,
      betragAbgelehnt: 147.20,
      erstattungsquote: 60,
      widerspruchEmpfohlen: true,
      widerspruchErklaerung: "AXA hat zwei Positionen pauschal abgelehnt. Für GOÄ A3695a (Analogziffer) ist die Ablehnung rechtlich angreifbar — vergleichbare Leistungen sind nach §6 Abs. 2 GOÄ abrechnungsfähig. Für GOÄ 3 + 6 (Kumulationsabzug) sollte eine ärztliche Stellungnahme eingeholt werden.",
      widerspruchErfolgswahrscheinlichkeit: 72,
      widerspruchBegruendung: "Sehr geehrte Damen und Herren,\n\nhiermit lege ich fristgerecht Widerspruch gegen Ihren Erstattungsbescheid vom 20.03.2025 (Ref. AXA-2025-001234) ein.\n\n**Zu GOÄ A3695a (Ablehnung: 74,00 €):**\nDie Ablehnung der Analogziffer A3695a ist nicht berechtigt. Gemäß §6 Abs. 2 GOÄ können Leistungen, die nicht im Gebührenverzeichnis enthalten sind, entsprechend einer nach Art, Kosten- und Zeitaufwand gleichwertigen Leistung berechnet werden. Das erweiterte Schilddrüsen-Antikörperpanel (Anti-TPO, Anti-Thyreoglobulin) entspricht dem Aufwand der Ziff. 3695 und ist medizinisch indiziert. Der BGH hat wiederholt bestätigt, dass Analogabrechnungen bei fehlender Regelleistung zulässig sind.\n\nIch bitte um Erstattung des gesamten Betrages von 74,00 € innerhalb von 4 Wochen.",
      naechsteSchritte: [
        "Dr. Hartmann kontaktieren: Stellungnahme zur gleichzeitigen Abrechnung GOÄ 3 + GOÄ 6 anfordern — konkret: medizinische Notwendigkeit beider Positionen am selben Termin begründen",
        "Widerspruchsbrief gegen Ablehnung GOÄ A3695a an AXA versenden (KI-Entwurf liegt bereit, bitte prüfen und absenden)",
        "Frist beachten: Widerspruch muss innerhalb von 6 Monaten nach Bescheiddatum eingehen (Frist: 20.09.2025)",
      ],
      zusammenfassung: "AXA hat 147,20 € (40% des eingereichten Betrags) nicht erstattet. Zwei Aktionen erforderlich: (1) Ärztliche Stellungnahme zu GOÄ 3+6 Kumulation beim Arzt anfordern. (2) Formeller Widerspruch gegen Analogziffer-Ablehnung A3695a — Erfolgswahrscheinlichkeit 72%.",
      ablehnungsgruende: [
        "GOÄ A3695a: Analogziffer — pauschale Ablehnung gemäß Tarifbedingungen (Ref. §4 AVB)",
        "GOÄ 3 + GOÄ 6: Kumulation gleichartiger Leistungen an einem Behandlungstag ohne Begründung",
      ],
      rechnungen: [
        {
          matchedVorgangId: "demo-1",
          arztName: "Dr. med. Klaus Hartmann",
          arztFachgebiet: "Innere Medizin",
          rechnungsnummer: null,
          rechnungsdatum: "2025-03-14",
          betragEingereicht: 218.47,
          betragErstattet: 145.27,
          betragAbgelehnt: 73.20,
          positionen: [
            {
              ziffer: "3",
              bezeichnung: "Eingehende Beratung (mind. 10 Min.)",
              betragEingereicht: 28.68,
              betragErstattet: 0,
              status: "abgelehnt" as const,
              ablehnungsgrund: "GOÄ 3 und GOÄ 6 können nicht gleichzeitig am selben Tag abgerechnet werden (Kumulationsausschluss)",
              aktionstyp: "korrektur_arzt" as const,
              widerspruchWahrscheinlichkeit: null,
              confidence: 85,
            },
            {
              ziffer: "5",
              bezeichnung: "Symptombezogene Untersuchung",
              betragEingereicht: 19.24,
              betragErstattet: 19.24,
              status: "erstattet" as const,
              aktionstyp: null,
            },
            {
              ziffer: "6",
              bezeichnung: "Vollständige körperliche Untersuchung",
              betragEingereicht: 16.88,
              betragErstattet: 16.88,
              status: "erstattet" as const,
              aktionstyp: null,
            },
            {
              ziffer: "75",
              bezeichnung: "Schutzimpfung (subkutan/intramuskulär)",
              betragEingereicht: 6.72,
              betragErstattet: 6.72,
              status: "erstattet" as const,
              aktionstyp: null,
            },
            {
              ziffer: "250",
              bezeichnung: "Blutentnahme durch Venenpunktion",
              betragEingereicht: 4.43,
              betragErstattet: 4.43,
              status: "erstattet" as const,
              aktionstyp: null,
            },
          ],
        },
        {
          matchedVorgangId: "demo-2",
          arztName: "Labor Müller GmbH",
          arztFachgebiet: "Labordiagnostik",
          rechnungsnummer: null,
          rechnungsdatum: "2025-03-02",
          betragEingereicht: 147.20,
          betragErstattet: 73.20,
          betragAbgelehnt: 74.00,
          positionen: [
            {
              ziffer: "3550",
              bezeichnung: "Hormonstatus: TSH, fT3, fT4",
              betragEingereicht: 73.20,
              betragErstattet: 73.20,
              status: "erstattet" as const,
              aktionstyp: null,
            },
            {
              ziffer: "A3695a",
              bezeichnung: "Erweitertes Hormonpanel (Analogziffer) — Anti-TPO, Anti-Thyreoglobulin",
              betragEingereicht: 74.00,
              betragErstattet: 0,
              status: "abgelehnt" as const,
              ablehnungsgrund: "Analogziffer — nicht im Leistungskatalog des Tarifs ActiveMe-U enthalten (§4 AVB)",
              aktionstyp: "widerspruch_kasse" as const,
              widerspruchWahrscheinlichkeit: 72,
              confidence: 78,
            },
          ],
        },
      ],
    },
    rechnungen: [
      {
        matchedVorgangId: "demo-1",
        arztName: "Dr. med. Klaus Hartmann",
        arztFachgebiet: "Innere Medizin",
        rechnungsnummer: null,
        rechnungsdatum: "2025-03-14",
        betragEingereicht: 218.47,
        betragErstattet: 145.27,
        betragAbgelehnt: 73.20,
        positionen: [
          {
            ziffer: "3",
            bezeichnung: "Eingehende Beratung (mind. 10 Min.)",
            betragEingereicht: 28.68,
            betragErstattet: 0,
            status: "abgelehnt" as const,
            ablehnungsgrund: "GOÄ 3 und GOÄ 6 gleichzeitig — Kumulationsausschluss",
            aktionstyp: "korrektur_arzt" as const,
            widerspruchWahrscheinlichkeit: null,
            confidence: 85,
          },
          { ziffer: "5", bezeichnung: "Symptombezogene Untersuchung", betragEingereicht: 19.24, betragErstattet: 19.24, status: "erstattet" as const, aktionstyp: null },
          { ziffer: "6", bezeichnung: "Vollständige körperliche Untersuchung", betragEingereicht: 16.88, betragErstattet: 16.88, status: "erstattet" as const, aktionstyp: null },
          { ziffer: "75", bezeichnung: "Schutzimpfung", betragEingereicht: 6.72, betragErstattet: 6.72, status: "erstattet" as const, aktionstyp: null },
          { ziffer: "250", bezeichnung: "Blutentnahme", betragEingereicht: 4.43, betragErstattet: 4.43, status: "erstattet" as const, aktionstyp: null },
        ],
      },
      {
        matchedVorgangId: "demo-2",
        arztName: "Labor Müller GmbH",
        arztFachgebiet: "Labordiagnostik",
        rechnungsnummer: null,
        rechnungsdatum: "2025-03-02",
        betragEingereicht: 147.20,
        betragErstattet: 73.20,
        betragAbgelehnt: 74.00,
        positionen: [
          { ziffer: "3550", bezeichnung: "Hormonstatus: TSH, fT3, fT4", betragEingereicht: 73.20, betragErstattet: 73.20, status: "erstattet" as const, aktionstyp: null },
          {
            ziffer: "A3695a",
            bezeichnung: "Erweitertes Hormonpanel (Analogziffer) — Anti-TPO, Anti-Thyreoglobulin",
            betragEingereicht: 74.00,
            betragErstattet: 0,
            status: "abgelehnt" as const,
            ablehnungsgrund: "Analogziffer — nicht im Leistungskatalog des Tarifs ActiveMe-U",
            aktionstyp: "widerspruch_kasse" as const,
            widerspruchWahrscheinlichkeit: 72,
            confidence: 78,
          },
        ],
      },
    ],
    vorgaenge: [
      { id: "demo-1", arzt_name: "Dr. med. Klaus Hartmann", rechnungsdatum: "2025-03-14", rechnungsnummer: null, betrag_gesamt: 218.47, kasse_match_status: "teilweise_abgelehnt", pdf_storage_path: null },
      { id: "demo-2", arzt_name: "Labor Müller GmbH", rechnungsdatum: "2025-03-02", rechnungsnummer: null, betrag_gesamt: 147.20, kasse_match_status: "teilweise_abgelehnt", pdf_storage_path: null },
    ],
  },
  {
    id: "demo-kasse-2",
    bescheiddatum: "2025-03-05",
    referenznummer: "AXA-2025-000987",
    betrag_eingereicht: 214.00,
    betrag_erstattet: 214.00,
    betrag_abgelehnt: 0,
    widerspruch_empfohlen: false,
    widerspruch_status: null,
    arzt_reklamation_status: "keiner",
    selbstbehalt_abgezogen: null,
    selbstbehalt_verbleibend: null,
    selbstbehalt_jahresgrenze: null,
    pdf_storage_path: null,
    kasse_analyse: {
      referenznummer: "AXA-2025-000987",
      bescheiddatum: "2025-03-05",
      betragEingereicht: 214.00,
      betragErstattet: 214.00,
      betragAbgelehnt: 0,
      erstattungsquote: 100,
      widerspruchEmpfohlen: false,
      widerspruchErklaerung: null,
      widerspruchErfolgswahrscheinlichkeit: null,
      naechsteSchritte: null,
      zusammenfassung: "Vollständige Erstattung — keine Auffälligkeiten. AXA hat alle 2 Positionen korrekt und fristgerecht erstattet.",
      ablehnungsgruende: [],
      rechnungen: [
        {
          matchedVorgangId: "demo-3",
          arztName: "Dr. med. Julia Schulz",
          arztFachgebiet: "Dermatologie",
          rechnungsnummer: null,
          rechnungsdatum: "2025-02-18",
          betragEingereicht: 214.00,
          betragErstattet: 214.00,
          betragAbgelehnt: 0,
          positionen: [
            { ziffer: "750", bezeichnung: "Behandlung einer Hauterkrankung", betragEingereicht: 83.47, betragErstattet: 83.47, status: "erstattet" as const, aktionstyp: null },
            { ziffer: "760", bezeichnung: "Dermatologische Phototherapie (UVA/UVB)", betragEingereicht: 130.53, betragErstattet: 130.53, status: "erstattet" as const, aktionstyp: null },
          ],
        },
      ],
    },
    rechnungen: [
      {
        matchedVorgangId: "demo-3",
        arztName: "Dr. med. Julia Schulz",
        arztFachgebiet: "Dermatologie",
        rechnungsnummer: null,
        rechnungsdatum: "2025-02-18",
        betragEingereicht: 214.00,
        betragErstattet: 214.00,
        betragAbgelehnt: 0,
        positionen: [
          { ziffer: "750", bezeichnung: "Behandlung einer Hauterkrankung", betragEingereicht: 83.47, betragErstattet: 83.47, status: "erstattet" as const, aktionstyp: null },
          { ziffer: "760", bezeichnung: "Dermatologische Phototherapie", betragEingereicht: 130.53, betragErstattet: 130.53, status: "erstattet" as const, aktionstyp: null },
        ],
      },
    ],
    vorgaenge: [
      { id: "demo-3", arzt_name: "Dr. med. Julia Schulz", rechnungsdatum: "2025-02-18", rechnungsnummer: null, betrag_gesamt: 214.00, kasse_match_status: "erstattet", pdf_storage_path: null },
    ],
  },
];

// ── Mock Widerspruchsverfahren ────────────────────────────────────────────────
export const mockWiderspruchFaelle: WiderspruchFall[] = [
  {
    id: "demo-widerspruch-1",
    bescheiddatum: "2025-03-20",
    referenznummer: "AXA-2025-001234",
    betrag_eingereicht: 147.20,
    betrag_erstattet: 73.20,
    betrag_abgelehnt: 74.00,
    betrag_widerspruch_kasse: 74.00,
    betrag_korrektur_arzt: null,
    widerspruch_status: "erstellt",
    arzt_reklamation_status: "keiner",
    widerspruch_gesendet_am: null,
    pdf_storage_path: null,
    kasse_analyse: {
      widerspruchEmpfohlen: true,
      widerspruchErfolgswahrscheinlichkeit: 72,
      widerspruchErklaerung: "AXA hat die Analogziffer GOÄ A3695a (erweitertes Hormonpanel) pauschal abgelehnt — das ist rechtlich angreifbar. Gemäß §6 Abs. 2 GOÄ darf ein Arzt Leistungen, die in der Gebührenordnung nicht aufgeführt sind, analog zu einer gleichwertigen Leistung abrechnen. AXA kann dies nicht einfach mit dem Hinweis auf „pauschale Nicht-Übernahme\" ablehnen. Die 72%ige Erfolgsquote bei ähnlichen Widersprüchen belegt: Dieser Widerspruch lohnt sich.",
      widerspruchBegruendung: "Sehr geehrte Damen und Herren,\n\nhiermit lege ich form- und fristgerecht Widerspruch gegen Ihren Erstattungsbescheid vom 20.03.2025 (Ref. AXA-2025-001234) ein.\n\nAblehnung GOÄ A3695a — Erweiterter Hormonstatus\n\nSie haben die Erstattung der Analogziffer GOÄ A3695a (Erweitertes Hormonpanel, Differentialdiagnostik Schilddrüsenfunktionsstörung) mit der Begründung abgelehnt, Analogziffern würden im Tarif ActiveMe-U „nicht pauschal übernommen\".\n\nDiese Ablehnung ist rechtlich nicht haltbar:\n\n1. Zulässigkeit der Analogabrechnung (§6 Abs. 2 GOÄ): Gemäß §6 Abs. 2 der Gebührenordnung für Ärzte ist der Arzt berechtigt, Leistungen, die in der Gebührenordnung nicht verzeichnet sind, entsprechend einer nach Art, Kosten- und Zeitaufwand gleichwertigen Leistung zu berechnen. Das Bundessozialgericht hat in seinem Urteil vom 17.07.2008 (Az. B 3 KR 16/07 R) bestätigt, dass diese Regelung auch für PKV-Verträge bindend ist, sofern der Tarif die GOÄ als Abrechnungsgrundlage vorsieht.\n\n2. Medizinische Notwendigkeit: Die Untersuchung wurde vom behandelnden Arzt als medizinisch notwendig angeordnet und dokumentiert. Eine pauschale Ablehnung ohne Prüfung der individuellen medizinischen Indikation verstößt gegen Ihre Leistungspflicht.\n\n3. Keine wirksame Ausschlussklausel: Ihr Tarifwerk enthält keine ausdrückliche und wirksame Klausel, die Analogleistungen nach §6 Abs. 2 GOÄ generell ausschließt. Eine solche Pauschalablehnung wäre als überraschende Klausel nach §305c BGB unwirksam.\n\nIch bitte Sie daher, den abgelehnten Betrag von 74,00 € nachzuerstatten und mir hierüber einen korrigierten Bescheid zuzusenden.\n\nSollten Sie an Ihrer Ablehnungsentscheidung festhalten, behalte ich mir vor, die Angelegenheit dem Ombudsmann Private Kranken- und Pflegeversicherung zur Prüfung vorzulegen sowie rechtliche Schritte einzuleiten.\n\nMit freundlichen Grüßen\n[Ihr Name]",
      zusammenfassung: "AXA hat 74,00 € (50 % des eingereichten Betrags) nicht erstattet. Die Ablehnung der Analogziffer A3695a ist rechtlich angreifbar — Widerspruch mit 72 % Erfolgswahrscheinlichkeit empfohlen.",
      naechsteSchritte: [
        "Widerspruchsbrief versenden: Den vorbereiteten Brief per Einschreiben/Rückschein an AXA senden — Frist: 20.05.2025 (2 Monate nach Bescheid).",
        "Arztattest beifügen: Labor Müller GmbH um eine kurze schriftliche Bestätigung der medizinischen Notwendigkeit der Hormondiagnostik bitten.",
        "Fristenkontrolle: Widerspruchsfrist endet am 20.05.2025 — spätestens bis 15.05.2025 absenden, damit der Poststempel passt.",
      ],
      ablehnungsgruende: [
        {
          ziffer: "A3695a",
          bezeichnung: "Erweitertes Hormonpanel (Analogziffer)",
          betrag: 74.00,
          grund: "Analogziffern werden im Tarif ActiveMe-U nicht pauschal übernommen.",
          einschaetzung: "Angreifbar — §6 Abs. 2 GOÄ erlaubt Analogabrechnung, pauschaler Ausschluss ist unwirksam.",
        },
      ],
      rechnungen: [
        {
          arztName: "Labor Müller GmbH",
          arztFachgebiet: "Labordiagnostik",
          rechnungsnummer: "LAB-2025-0302",
          rechnungsdatum: "2025-03-02",
          betragEingereicht: 147.20,
          betragErstattet: 73.20,
          betragAbgelehnt: 74.00,
          positionen: [
            {
              ziffer: "3550",
              bezeichnung: "Hormonstatus: TSH, fT3, fT4",
              betragEingereicht: 73.20,
              betragErstattet: 73.20,
              status: "erstattet" as const,
              aktionstyp: null,
            },
            {
              ziffer: "A3695a",
              bezeichnung: "Erweitertes Hormonpanel (Analogziffer §6 Abs. 2 GOÄ)",
              betragEingereicht: 74.00,
              betragErstattet: 0,
              status: "abgelehnt" as const,
              aktionstyp: "widerspruch_kasse" as const,
              widerspruchWahrscheinlichkeit: 72,
              confidence: 0.82,
              begruendung: "Pauschale Ablehnung von Analogziffern ist nach §6 Abs. 2 GOÄ und BGH-Rechtsprechung nicht zulässig. AXA muss die medizinische Notwendigkeit im Einzelfall prüfen.",
            },
          ],
        },
      ],
    },
    vorgaenge: [
      { id: "demo-2", arzt_name: "Labor Müller GmbH", rechnungsdatum: "2025-03-02", betrag_gesamt: 147.20 },
    ],
    kommunikationen: [
      {
        id: "demo-komm-1",
        kassenabrechnungen_id: "demo-widerspruch-1",
        richtung: "eingehend",
        kommunikationspartner: "kasse",
        typ: "bescheid",
        datum: "2025-03-20",
        betreff: "Erstattungsbescheid 20.03.2025",
        inhalt: "Bescheid über die Erstattung Ihrer eingereichten Belege. Die Position GOÄ A3695a (erweitertes Hormonpanel) kann leider nicht erstattet werden, da Analogziffern gemäß den Bedingungen Ihres Tarifs ActiveMe-U nicht pauschal übernommen werden. Alle übrigen Positionen wurden wie abgerechnet erstattet. Erstatteter Betrag: 73,20 €. Nicht erstatteter Betrag: 74,00 €.",
        ki_analyse: "⚠️ AXA begründet die Ablehnung mit einer pauschalen Tarifbedingung — das ist angreifbar. §6 Abs. 2 GOÄ gibt dem Arzt das Recht, nicht aufgeführte Leistungen analog abzurechnen. Ein allgemeiner Ausschluss aller Analogziffern ohne Einzelfallprüfung ist nach BGH-Rechtsprechung (Az. IV ZR 201/10) für PKV-Verträge unwirksam. Widerspruch lohnt sich — Erfolgswahrscheinlichkeit: 72 %.",
        ki_vorschlag_betreff: "Widerspruch gegen Ablehnung GOÄ A3695a — Erstattung 74,00 € (Ref. AXA-2025-001234)",
        ki_vorschlag_inhalt: "Sehr geehrte Damen und Herren,\n\nhiermit lege ich form- und fristgerecht Widerspruch gegen Ihren Erstattungsbescheid vom 20.03.2025 (Ref. AXA-2025-001234) ein.\n\n----------------------------\nABGELEHNTE POSITION: GOÄ A3695a\nBetrag: 74,00 €\n----------------------------\n\nIhre Ablehnung mit der Begründung, Analogziffern würden im Tarif ActiveMe-U „nicht pauschal übernommen\", ist rechtlich nicht haltbar. Im Einzelnen:\n\n1. ZULÄSSIGKEIT DER ANALOGABRECHNUNG (§6 Abs. 2 GOÄ)\nGemäß §6 Abs. 2 der Gebührenordnung für Ärzte (GOÄ) ist der Arzt berechtigt, Leistungen, die in der Gebührenordnung nicht verzeichnet sind, entsprechend einer nach Art, Kosten- und Zeitaufwand gleichwertigen Leistung zu berechnen. Diese Vorschrift ist bindender Bestandteil jedes PKV-Vertrags, der die GOÄ als Abrechnungsgrundlage vorsieht.\n\nDer Bundesgerichtshof hat in seinem Urteil vom 21.09.2011 (Az. IV ZR 201/10) ausdrücklich bestätigt, dass PKV-Versicherer Analogleistungen nach §6 Abs. 2 GOÄ nicht pauschal ausschließen dürfen, solange keine ausdrückliche und wirksame Individualvereinbarung vorliegt.\n\n2. MEDIZINISCHE NOTWENDIGKEIT\nDie erweiterte Hormondiagnostik (GOÄ A3695a) wurde von Labor Müller GmbH auf Anweisung des behandelnden Arztes zur Abklärung einer Schilddrüsenfunktionsstörung durchgeführt. Die medizinische Notwendigkeit ist durch die ärztliche Verordnung belegt.\n\n3. KEINE WIRKSAME AUSSCHLUSSKLAUSEL\nEin genereller Ausschluss von Analogleistungen stellt eine überraschende Klausel im Sinne von §305c BGB dar, die — mangels gesonderter Vereinbarung — keine Wirkung entfaltet.\n\nICH BITTE SIE DAHER:\n-> Den abgelehnten Betrag von 74,00 € nachzuerstatten\n-> Mir hierüber einen korrigierten Bescheid zuzusenden\n\nSollten Sie an Ihrer Entscheidung festhalten, behalte ich mir vor, den Ombudsmann Private Kranken- und Pflegeversicherung einzuschalten und ggf. rechtliche Schritte einzuleiten.\n\nMit freundlichen Grüßen\n[Ihr vollständiger Name]\n[Versicherungsnummer]\n[Datum]",
        ki_naechster_empfaenger: "kasse",
        ki_dringlichkeit: "hoch",
        ki_naechste_frist: "2025-05-15",
        created_at: "2025-03-21T10:00:00Z",
      },
    ],
  },
];

// ── Mock Ärzteakte (ArztAkteData[]) ──────────────────────────────────────────
export const mockAerzteDemoData: ArztAkteData[] = [
  {
    id: "demo-arzt-hartmann",
    name: "Dr. med. Klaus Hartmann",
    fachrichtung: "Innere Medizin",
    ersterBesuch: "12.06.2024",
    letzterBesuch: "14.03.2025",
    besuche: 4,
    gesamtBetrag: 687,
    eingereichtBeiKasse: 475,
    erstattetVonKasse: 412,
    abgelehntVonKasse: 63,
    ablehnungsquote: 13,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Jun '24", betrag: 186, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
      { datum: "Sep '24", betrag: 154, erstattet: 154, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
      { datum: "Nov '24", betrag: 128, erstattet: 128, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
      { datum: "Mär '25", betrag: 218, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
    ],
    goaMuster: [
      { ziffer: "3", bezeichnung: "Eingehende Beratung (>10 Min.)", haeufigkeit: 4, avgFaktor: 2.9, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "6", bezeichnung: "Vollständige körperliche Untersuchung", haeufigkeit: 4, avgFaktor: 3.2, axaAblehnungsrate: 12, risiko: "hoch" },
      { ziffer: "5", bezeichnung: "Symptombezogene Untersuchung", haeufigkeit: 2, avgFaktor: 2.1, axaAblehnungsrate: 0, risiko: "ok" },
    ],
    benchmarkAblehnung: {
      thisArzt: 13,
      vergleichswert: 11,
      label: "Ø Innere Medizin (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024 (n=4.200 Patienten)",
      unit: "%",
    },
    benchmarkKasse: {
      thisArzt: 13,
      vergleichswert: 9,
      label: "Ø alle Ärzte bei AXA",
      quelle: "AXA-Benchmarkdaten 2024",
      unit: "%",
    },
    benchmarkFaktor: {
      thisArzt: 2.9,
      vergleichswert: 2.3,
      label: "Ø GOÄ-Faktor Innere Medizin (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "×",
    },
    benchmarkKosten: {
      thisArzt: 172,
      vergleichswert: 145,
      label: "Ø Kosten je Besuch Innere Medizin (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "€",
    },
    offeneAktionen: [
      { typ: "rechnung_flagged", label: "GOÄ-Auffälligkeit: Rechnung vom 14.03.2025 (Faktor 3,5×)", href: "/rechnungen", prioritaet: "hoch" },
    ],
    flagged: true,
  },
  {
    id: "demo-arzt-schulz",
    name: "Dr. med. Julia Schulz",
    fachrichtung: "Dermatologie",
    ersterBesuch: "08.02.2024",
    letzterBesuch: "18.02.2025",
    besuche: 2,
    gesamtBetrag: 312,
    eingereichtBeiKasse: 214,
    erstattetVonKasse: 214,
    abgelehntVonKasse: 0,
    ablehnungsquote: 0,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Feb '24", betrag: 98, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
      { datum: "Feb '25", betrag: 214, erstattet: 214, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
    ],
    goaMuster: [
      { ziffer: "750", bezeichnung: "Dermatologische Behandlung", haeufigkeit: 2, avgFaktor: 2.1, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "760", bezeichnung: "Phototherapie", haeufigkeit: 1, avgFaktor: 2.3, axaAblehnungsrate: null, risiko: "ok" },
    ],
    benchmarkAblehnung: {
      thisArzt: 0,
      vergleichswert: 8,
      label: "Ø Dermatologie (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024",
      unit: "%",
    },
    benchmarkKasse: null,
    benchmarkFaktor: {
      thisArzt: 2.1,
      vergleichswert: 2.2,
      label: "Ø GOÄ-Faktor Dermatologie (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "×",
    },
    benchmarkKosten: null,
    offeneAktionen: [],
    flagged: false,
  },
  {
    id: "demo-arzt-labor",
    name: "Labor Müller GmbH",
    fachrichtung: "Labordiagnostik",
    ersterBesuch: "02.03.2025",
    letzterBesuch: "02.03.2025",
    besuche: 1,
    gesamtBetrag: 147,
    eingereichtBeiKasse: 147,
    erstattetVonKasse: 73,
    abgelehntVonKasse: 74,
    ablehnungsquote: 50,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Mär '25", betrag: 147, erstattet: 73, abgelehnt: 74, ablehnungsquote: 50, hasBescheid: true },
    ],
    goaMuster: [
      { ziffer: "3550", bezeichnung: "Hormonstatus (TSH, fT3, fT4)", haeufigkeit: 1, avgFaktor: 1.0, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "A3695a", bezeichnung: "Erweitertes Hormonpanel (Analogziffer)", haeufigkeit: 1, avgFaktor: 1.0, axaAblehnungsrate: 100, risiko: "hoch" },
    ],
    benchmarkAblehnung: {
      thisArzt: 50,
      vergleichswert: 14,
      label: "Ø Labordiagnostik (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024",
      unit: "%",
    },
    benchmarkKasse: null,
    benchmarkFaktor: null,
    benchmarkKosten: null,
    offeneAktionen: [
      { typ: "widerspruch_offen", label: "Kassenwiderspruch erstellt, noch nicht gesendet", href: "/widersprueche", prioritaet: "hoch" },
    ],
    flagged: true,
  },
];
