import type { DashboardData } from "@/types";
import type { KasseBescheid } from "@/app/kassenabrechnung/page";
import type { WiderspruchFall } from "@/app/widersprueche/page";
import type { ArztAkteData } from "@/app/aerzte/AerzteClient";

export const mockDashboard: DashboardData = {
  user: { name: "Alexander S.", tarif: "ActiveMed-U", kasse: "AXA" },
  currentYear: new Date().getFullYear(),
  vorgangCount: 7,
  einsparpotenzialCount: 3,
  monthsWithData: 4,
  jahresausgaben: 1847,
  eigenanteil: 312,
  eigenanteilBreakdown: {
    abgelehnt: 87,
    stilleKuerzungen: 127,
    selbstbehalt: 150,
    offeneRechnungen: 0,
  },
  // Erstattungsquote = erstattet / (eingereicht - selbstbehalt) = 620/(820-150) ≈ 93%
  erstattungsquote: 93,
  einsparpotenzial: 63,              // GOÄ §12 Ärzte (rein GOÄ-basiert)
  widerspruchPotenzialKasse: 74,     // Positionen aktionstyp=widerspruch_kasse (Labor-Ablehnung)
  korrekturArztPotenzial: 63,
  widerspruchVerfahren: [],
  // Prognose: data through month 4 (April) → × 12/4
  prognose: Math.round(1847 / 4 * 12),
  vorgaenge: [
    {
      id: "1",
      datum: "14.03.2025",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 218.47,
      einsparpotenzial: 63.80,
      status: "pruefen",
      goaZiffern: ["GOÄ 3", "GOÄ 5", "GOÄ 6"],
      faktor: 3.5,
      flagged: true,
      flagReason: "Faktor 3,5× ohne §12-Begründung",
    },
    {
      id: "2",
      datum: "02.03.2025",
      arzt: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      betrag: 147.20,
      einsparpotenzial: 74.00,
      status: "abgelehnt",
      goaZiffern: ["GOÄ 3550", "GOÄ A3695a"],
      flagged: true,
      flagReason: "Analogziffer AXA-Ablehnung",
    },
    {
      id: "3",
      datum: "18.02.2025",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 214.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 750", "GOÄ 760"],
      faktor: 2.1,
    },
    {
      id: "4",
      datum: "05.01.2025",
      arzt: "Praxis Zentrum Sehen",
      fachrichtung: "Augenheilkunde",
      betrag: 152.00,
      status: "erstattet",
      goaZiffern: ["GOÄ 1200", "GOÄ 1240"],
      faktor: 1.8,
    },
    {
      id: "5",
      datum: "12.06.2024",
      arzt: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      betrag: 186.40,
      status: "erstattet",
      faktor: 3.0,
      flagged: true,
      flagReason: "Faktor 3,0× ohne §12-Begründung",
    },
    {
      id: "6",
      datum: "08.02.2024",
      arzt: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      betrag: 98.50,
      status: "erstattet",
      faktor: 2.3,
    },
  ],
  aerzte: [
    {
      id: "hartmann",
      name: "Dr. med. Klaus Hartmann",
      fachrichtung: "Innere Medizin",
      ort: "München",
      besuche: 4,
      gesamtBetrag: 687,
      avgFaktor: 2.9,
      flagged: true,
      erstattetVonKasse: 412,
      abgelehntVonKasse: 63,
      eingereichtBeiKasse: 475,
      faktorVerlauf: [
        { datum: "Mär '23", faktor: 1.8 },
        { datum: "Nov '23", faktor: 2.3 },
        { datum: "Jun '24", faktor: 3.0 },
        { datum: "Mär '25", faktor: 3.5 },
      ],
      alerts: [
        "Faktor stieg von 1,8× auf 3,5× — ohne §12-Begründung",
        "GOÄ Nr. 3 + Nr. 6 gleichzeitig abgerechnet (unplausible Kumulation, <3% der Internisten)",
      ],
    },
    {
      id: "schulz",
      name: "Dr. med. Julia Schulz",
      fachrichtung: "Dermatologie",
      ort: "München",
      besuche: 2,
      gesamtBetrag: 214,
      avgFaktor: 2.2,
      flagged: false,
      erstattetVonKasse: 198,
      abgelehntVonKasse: 0,
      eingereichtBeiKasse: 198,
      faktorVerlauf: [
        { datum: "Feb '24", faktor: 2.3 },
        { datum: "Feb '25", faktor: 2.1 },
      ],
      alerts: [],
    },
    {
      id: "labor",
      name: "Labor Müller GmbH",
      fachrichtung: "Labordiagnostik",
      ort: "München",
      besuche: 3,
      gesamtBetrag: 312,
      avgFaktor: 1.0,
      flagged: true,
      erstattetVonKasse: 73,
      abgelehntVonKasse: 74,
      eingereichtBeiKasse: 147,
      faktorVerlauf: [],
      alerts: ["38% Ablehnungsrate bei AXA für Analogziffer A3695a"],
    },
  ],
  kasse: {
    kasseName: "AXA",
    erstattungsquote: 93,
    erstattungsquoteAvg: 89,
    ablehnungsrate: [0, 18],  // 2 points: start-of-year baseline vs current month
    ablehnungsrateReal: 18,
    stilleKuerzungTotal: 127,
    stilleKuerzungCount: 5,
    stilleKuerzungen: [
      { kategorie: "Laborpositionen", betrag: 74, vorgaenge: 3 },
      { kategorie: "Internist Faktoren", betrag: 38, vorgaenge: 2 },
      { kategorie: "Sonstige", betrag: 15, vorgaenge: 2 },
    ],
    totalAbgelehnt: 147,
    totalSelbstbehalt: 150,
    widerspruchPotenzial: 147,
    fachgruppenStats: [
      { fach: "Innere Medizin", vorgaenge: 3, eingereicht: 687, abgelehnt: 127, ablehnungsquote: 18 },
      { fach: "Labor",          vorgaenge: 4, eingereicht: 312, abgelehnt: 74,  ablehnungsquote: 24 },
      { fach: "Dermatologie",   vorgaenge: 2, eingereicht: 214, abgelehnt: 0,   ablehnungsquote: 0  },
    ],
  },
  ausgabenNachFach: [
    { fach: "Innere Medizin", betrag: 687, icon: "❤️", farbe: "#fca5a5" },
    { fach: "Labor", betrag: 312, icon: "🔬", farbe: "#c4b5fd" },
    { fach: "Dermatologie", betrag: 214, icon: "🧬", farbe: "#93c5fd" },
    { fach: "Augenheilkunde", betrag: 152, icon: "👁️", farbe: "#6ee7b7" },
    { fach: "Weitere", betrag: 482, icon: "💊", farbe: "#e2e8f0" },
  ],
  vorsorgeLeistungen: [
    {
      id: "v1",
      name: "Internist Jahres-Check",
      icon: "❤️",
      fachgebiet: "Innere Medizin",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-14",
      naechstesDatum: "2026-03-14",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v2",
      name: "Labor-Basisprofil",
      icon: "🔬",
      fachgebiet: "Labordiagnostik",
      empfIntervallMonate: 12,
      letzteDatum: "2025-03-02",
      naechstesDatum: "2026-03-02",
      status: "bald",
      axaLeistung: true,
    },
    {
      id: "v3",
      name: "Augenarzt Sehtest",
      icon: "👁️",
      fachgebiet: "Augenheilkunde",
      empfIntervallMonate: 24,
      letzteDatum: "2025-01-05",
      naechstesDatum: "2027-01-05",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v4",
      name: "Dermatologie Hautscreening",
      icon: "🧬",
      fachgebiet: "Dermatologie",
      empfIntervallMonate: 24,
      letzteDatum: "2025-02-18",
      naechstesDatum: "2027-02-18",
      status: "ok",
      axaLeistung: true,
    },
    {
      id: "v5",
      name: "Zahnarzt Prophylaxe",
      icon: "🦷",
      fachgebiet: "Zahnarzt",
      empfIntervallMonate: 6,
      letzteDatum: null,
      naechstesDatum: null,
      status: "faellig",
      axaLeistung: true,
    },
  ],
};

// ── Mock Rechnungen (VorgangRow shape for RechnungenClient) ──────────────────
export const mockRechnungen = [
  {
    id: "demo-1",
    datum: "14.03.2025",
    arzt: "Dr. med. Klaus Hartmann",
    fachrichtung: "Innere Medizin",
    betrag: 218.47,
    betragErstattet: undefined,
    einsparpotenzial: 63.80,
    status: "pruefen",
    flagged: true,
    flagReason: "Faktor 3,5× ohne §12-Begründung",
    faktor: 3.5,
    goaZiffern: ["GOÄ 3", "GOÄ 5", "GOÄ 6"],
    hasPdf: false,
    hasKassePdf: false,
    claudeAnalyse: null,
    kasseAnalyse: null,
    kassenbescheid: null,
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-2",
    datum: "02.03.2025",
    arzt: "Labor Müller GmbH",
    fachrichtung: "Labordiagnostik",
    betrag: 147.20,
    betragErstattet: 73.20,
    einsparpotenzial: 74.00,
    status: "abgelehnt",
    flagged: true,
    flagReason: "Analogziffer AXA-Ablehnung",
    faktor: undefined,
    goaZiffern: ["GOÄ 3550", "GOÄ A3695a"],
    hasPdf: false,
    hasKassePdf: true,
    claudeAnalyse: null,
    kasseAnalyse: null,
    kassenbescheid: {
      id: "demo-kasse-1",
      bescheiddatum: "2025-03-20",
      referenznummer: "AXA-2025-001234",
      betragErstattet: 73.20,
      betragAbgelehnt: 74.00,
      widerspruchEmpfohlen: true,
      widerspruchStatus: "erstellt",
      widerspruchErfolgswahrscheinlichkeit: 72,
    },
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-3",
    datum: "18.02.2025",
    arzt: "Dr. med. Julia Schulz",
    fachrichtung: "Dermatologie",
    betrag: 214.00,
    betragErstattet: 214.00,
    einsparpotenzial: undefined,
    status: "erstattet",
    flagged: false,
    flagReason: undefined,
    faktor: 2.1,
    goaZiffern: ["GOÄ 750", "GOÄ 760"],
    hasPdf: false,
    hasKassePdf: true,
    claudeAnalyse: null,
    kasseAnalyse: null,
    kassenbescheid: {
      id: "demo-kasse-2",
      bescheiddatum: "2025-03-05",
      referenznummer: "AXA-2025-000987",
      betragErstattet: 214.00,
      betragAbgelehnt: 0,
      widerspruchEmpfohlen: false,
      widerspruchStatus: "keiner",
      widerspruchErfolgswahrscheinlichkeit: null,
    },
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
  {
    id: "demo-4",
    datum: "05.01.2025",
    arzt: "Praxis Zentrum Sehen",
    fachrichtung: "Augenheilkunde",
    betrag: 152.00,
    betragErstattet: 152.00,
    einsparpotenzial: undefined,
    status: "erstattet",
    flagged: false,
    flagReason: undefined,
    faktor: 1.8,
    goaZiffern: ["GOÄ 1200", "GOÄ 1240"],
    hasPdf: false,
    hasKassePdf: false,
    claudeAnalyse: null,
    kasseAnalyse: null,
    kassenbescheid: null,
    kasseGruppe: null,
    kasseAnalyseNew: null,
  },
] as const;

// ── Mock Kassenabrechnungen ───────────────────────────────────────────────────
export const mockKasseBescheide: KasseBescheid[] = [
  {
    id: "demo-kasse-1",
    bescheiddatum: "2025-03-20",
    referenznummer: "AXA-2025-001234",
    betrag_eingereicht: 365.67,
    betrag_erstattet: 218.47,
    betrag_abgelehnt: 147.20,
    widerspruch_empfohlen: true,
    widerspruch_status: "erstellt",
    arzt_reklamation_status: "keiner",
    selbstbehalt_abgezogen: null,
    selbstbehalt_verbleibend: null,
    selbstbehalt_jahresgrenze: null,
    pdf_storage_path: null,
    kasse_analyse: {
      widerspruchErfolgswahrscheinlichkeit: 72,
      zusammenfassung: "AXA hat 2 Laborpositionen (Analogziffern) vollständig abgelehnt. Widerspruch empfohlen.",
      aktionen: [
        { typ: "widerspruch_kasse", beschreibung: "Widerspruch gegen Ablehnung GOÄ A3695a (Analogziffer)", betrag: 74.00 },
      ],
    },
    rechnungen: [
      {
        matchedVorgangId: "demo-1",
        arztName: "Dr. med. Klaus Hartmann",
        arztFachgebiet: "Innere Medizin",
        rechnungsnummer: null,
        rechnungsdatum: "2025-03-14",
        betragEingereicht: 218.47,
        betragErstattet: 218.47,
        betragAbgelehnt: 0,
        positionen: [],
      },
      {
        matchedVorgangId: "demo-2",
        arztName: "Labor Müller GmbH",
        arztFachgebiet: "Labordiagnostik",
        rechnungsnummer: null,
        rechnungsdatum: "2025-03-02",
        betragEingereicht: 147.20,
        betragErstattet: 73.20,
        betragAbgelehnt: 74.00,
        positionen: [
          { ziffer: "3550", bezeichnung: "Hormonstatus", status: "erstattet" as const, betragEingereicht: 73.20, betragErstattet: 73.20 },
          { ziffer: "A3695a", bezeichnung: "Erweitertes Labor-Analogpanel", status: "abgelehnt" as const, betragEingereicht: 74.00, betragErstattet: 0, ablehnungsgrund: "Analogziffer nicht erstattungsfähig gemäß Tarif" },
        ],
      },
    ],
    vorgaenge: [
      { id: "demo-1", arzt_name: "Dr. med. Klaus Hartmann", rechnungsdatum: "2025-03-14", rechnungsnummer: null, betrag_gesamt: 218.47, kasse_match_status: "erstattet", pdf_storage_path: null },
      { id: "demo-2", arzt_name: "Labor Müller GmbH", rechnungsdatum: "2025-03-02", rechnungsnummer: null, betrag_gesamt: 147.20, kasse_match_status: "teilweise_abgelehnt", pdf_storage_path: null },
    ],
  },
  {
    id: "demo-kasse-2",
    bescheiddatum: "2025-03-05",
    referenznummer: "AXA-2025-000987",
    betrag_eingereicht: 214.00,
    betrag_erstattet: 214.00,
    betrag_abgelehnt: 0,
    widerspruch_empfohlen: false,
    widerspruch_status: null,
    arzt_reklamation_status: "keiner",
    selbstbehalt_abgezogen: null,
    selbstbehalt_verbleibend: null,
    selbstbehalt_jahresgrenze: null,
    pdf_storage_path: null,
    kasse_analyse: {
      zusammenfassung: "Vollständige Erstattung. Keine Auffälligkeiten.",
    },
    rechnungen: [
      {
        matchedVorgangId: "demo-3",
        arztName: "Dr. med. Julia Schulz",
        arztFachgebiet: "Dermatologie",
        rechnungsnummer: null,
        rechnungsdatum: "2025-02-18",
        betragEingereicht: 214.00,
        betragErstattet: 214.00,
        betragAbgelehnt: 0,
        positionen: [],
      },
    ],
    vorgaenge: [
      { id: "demo-3", arzt_name: "Dr. med. Julia Schulz", rechnungsdatum: "2025-02-18", rechnungsnummer: null, betrag_gesamt: 214.00, kasse_match_status: "erstattet", pdf_storage_path: null },
    ],
  },
];

// ── Mock Widerspruchsverfahren ────────────────────────────────────────────────
export const mockWiderspruchFaelle: WiderspruchFall[] = [
  {
    id: "demo-widerspruch-1",
    bescheiddatum: "2025-03-20",
    referenznummer: "AXA-2025-001234",
    betrag_eingereicht: 147.20,
    betrag_erstattet: 73.20,
    betrag_abgelehnt: 74.00,
    betrag_widerspruch_kasse: 74.00,
    betrag_korrektur_arzt: null,
    widerspruch_status: "erstellt",
    arzt_reklamation_status: "keiner",
    widerspruch_gesendet_am: null,
    pdf_storage_path: null,
    kasse_analyse: {
      widerspruchErfolgswahrscheinlichkeit: 72,
      widerspruchBegruendung: "Die abgelehnte Analogziffer A3695a (erweitertes Hormonpanel) ist nach GOÄ §6 Abs. 2 zulässig. Die Leistung ist medizinisch notwendig und in der Gebührenordnung nicht aufgeführt. Vergleichbare Leistungen rechtfertigen den Ansatz.",
    },
    vorgaenge: [
      { id: "demo-2", arzt_name: "Labor Müller GmbH", rechnungsdatum: "2025-03-02", betrag_gesamt: 147.20 },
    ],
    kommunikationen: [
      {
        id: "demo-komm-1",
        kassenabrechnungen_id: "demo-widerspruch-1",
        richtung: "eingehend",
        kommunikationspartner: "kasse",
        typ: "bescheid",
        datum: "2025-03-20",
        betreff: "Erstattungsbescheid 20.03.2025",
        inhalt: "Die Position GOÄ A3695a kann nicht erstattet werden, da Analogziffern im Tarif ActiveMe-U nicht pauschal übernommen werden.",
        ki_analyse: null,
        ki_vorschlag_betreff: "Widerspruch: Ablehnung GOÄ A3695a (Analogziffer, §6 Abs. 2)",
        ki_vorschlag_inhalt: "Sehr geehrte Damen und Herren,\n\nhiermit lege ich Widerspruch gegen den Bescheid vom 20.03.2025 ein...",
        ki_naechster_empfaenger: "kasse",
        ki_dringlichkeit: "hoch",
        ki_naechste_frist: "2025-05-20",
        created_at: "2025-03-21T10:00:00Z",
      },
    ],
  },
];

// ── Mock Ärzteakte (ArztAkteData[]) ──────────────────────────────────────────
export const mockAerzteDemoData: ArztAkteData[] = [
  {
    id: "demo-arzt-hartmann",
    name: "Dr. med. Klaus Hartmann",
    fachrichtung: "Innere Medizin",
    ersterBesuch: "12.06.2024",
    letzterBesuch: "14.03.2025",
    besuche: 4,
    gesamtBetrag: 687,
    eingereichtBeiKasse: 475,
    erstattetVonKasse: 412,
    abgelehntVonKasse: 63,
    ablehnungsquote: 13,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Jun '24", betrag: 186, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
      { datum: "Sep '24", betrag: 154, erstattet: 154, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
      { datum: "Nov '24", betrag: 128, erstattet: 128, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
      { datum: "Mär '25", betrag: 218, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
    ],
    goaMuster: [
      { ziffer: "3", bezeichnung: "Eingehende Beratung (>10 Min.)", haeufigkeit: 4, avgFaktor: 2.9, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "6", bezeichnung: "Vollständige körperliche Untersuchung", haeufigkeit: 4, avgFaktor: 3.2, axaAblehnungsrate: 12, risiko: "hoch" },
      { ziffer: "5", bezeichnung: "Symptombezogene Untersuchung", haeufigkeit: 2, avgFaktor: 2.1, axaAblehnungsrate: 0, risiko: "ok" },
    ],
    benchmarkAblehnung: {
      thisArzt: 13,
      vergleichswert: 11,
      label: "Ø Innere Medizin (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024 (n=4.200 Patienten)",
      unit: "%",
    },
    benchmarkKasse: {
      thisArzt: 13,
      vergleichswert: 9,
      label: "Ø alle Ärzte bei AXA",
      quelle: "AXA-Benchmarkdaten 2024",
      unit: "%",
    },
    benchmarkFaktor: {
      thisArzt: 2.9,
      vergleichswert: 2.3,
      label: "Ø GOÄ-Faktor Innere Medizin (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "×",
    },
    benchmarkKosten: {
      thisArzt: 172,
      vergleichswert: 145,
      label: "Ø Kosten je Besuch Innere Medizin (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "€",
    },
    offeneAktionen: [
      { typ: "rechnung_flagged", label: "GOÄ-Auffälligkeit: Rechnung vom 14.03.2025 (Faktor 3,5×)", href: "/rechnungen", prioritaet: "hoch" },
    ],
    flagged: true,
  },
  {
    id: "demo-arzt-schulz",
    name: "Dr. med. Julia Schulz",
    fachrichtung: "Dermatologie",
    ersterBesuch: "08.02.2024",
    letzterBesuch: "18.02.2025",
    besuche: 2,
    gesamtBetrag: 312,
    eingereichtBeiKasse: 214,
    erstattetVonKasse: 214,
    abgelehntVonKasse: 0,
    ablehnungsquote: 0,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Feb '24", betrag: 98, erstattet: null, abgelehnt: null, ablehnungsquote: null, hasBescheid: false },
      { datum: "Feb '25", betrag: 214, erstattet: 214, abgelehnt: 0, ablehnungsquote: 0, hasBescheid: true },
    ],
    goaMuster: [
      { ziffer: "750", bezeichnung: "Dermatologische Behandlung", haeufigkeit: 2, avgFaktor: 2.1, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "760", bezeichnung: "Phototherapie", haeufigkeit: 1, avgFaktor: 2.3, axaAblehnungsrate: null, risiko: "ok" },
    ],
    benchmarkAblehnung: {
      thisArzt: 0,
      vergleichswert: 8,
      label: "Ø Dermatologie (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024",
      unit: "%",
    },
    benchmarkKasse: null,
    benchmarkFaktor: {
      thisArzt: 2.1,
      vergleichswert: 2.2,
      label: "Ø GOÄ-Faktor Dermatologie (PKV)",
      quelle: "PKV-Benchmark 2024",
      unit: "×",
    },
    benchmarkKosten: null,
    offeneAktionen: [],
    flagged: false,
  },
  {
    id: "demo-arzt-labor",
    name: "Labor Müller GmbH",
    fachrichtung: "Labordiagnostik",
    ersterBesuch: "02.03.2025",
    letzterBesuch: "02.03.2025",
    besuche: 1,
    gesamtBetrag: 147,
    eingereichtBeiKasse: 147,
    erstattetVonKasse: 73,
    abgelehntVonKasse: 74,
    ablehnungsquote: 50,
    hatKassenbescheid: true,
    verlauf: [
      { datum: "Mär '25", betrag: 147, erstattet: 73, abgelehnt: 74, ablehnungsquote: 50, hasBescheid: true },
    ],
    goaMuster: [
      { ziffer: "3550", bezeichnung: "Hormonstatus (TSH, fT3, fT4)", haeufigkeit: 1, avgFaktor: 1.0, axaAblehnungsrate: 0, risiko: "ok" },
      { ziffer: "A3695a", bezeichnung: "Erweitertes Hormonpanel (Analogziffer)", haeufigkeit: 1, avgFaktor: 1.0, axaAblehnungsrate: 100, risiko: "hoch" },
    ],
    benchmarkAblehnung: {
      thisArzt: 50,
      vergleichswert: 14,
      label: "Ø Labordiagnostik (PKV, kassenübergreifend)",
      quelle: "PKV-Benchmark 2024",
      unit: "%",
    },
    benchmarkKasse: null,
    benchmarkFaktor: null,
    benchmarkKosten: null,
    offeneAktionen: [
      { typ: "widerspruch_offen", label: "Kassenwiderspruch erstellt, noch nicht gesendet", href: "/widersprueche", prioritaet: "hoch" },
    ],
    flagged: true,
  },
];
